// app/blog/[slug]/page.tsx
import { getPost, getPostSlugs } from "@/lib/posts";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { format } from "date-fns";

// Generate static paths for all your blog posts
export async function generateStaticParams() {
  const slugs = getPostSlugs();
  return slugs.map((slug) => ({ slug }));
}

// ---- NEW: Dynamic Metadata for SEO ----
type Props = {
  params: Promise<{ slug: string }>;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const post = getPost(slug);

  if (!post) {
    return {
      title: "Post Not Found",
    };
  }

  const postUrl = `https://tremonte.info/blog/${slug}`;

  return {
    title: post.title,
    description: post.excerpt || post.description || `Read ${post.title} on Tremonte.info`,
    openGraph: {
      title: post.title,
      description: post.excerpt || post.description || `Read ${post.title} on Tremonte.info`,
      type: "article",
      publishedTime: post.publishedAt,
      modifiedTime: post.updatedAt || post.publishedAt,
      authors: ["Tremonte"], // Change this to your name if you want
      url: postUrl,
      images: [
        {
          url: `/blog/${slug}/opengraph-image.png`, // Auto-generated by next file
          width: 1200,
          height: 630,
          alt: post.title,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: post.title,
      description: post.excerpt || post.description || `Read ${post.title} on Tremonte.info`,
      images: [`/blog/${slug}/opengraph-image.png`],
    },
  };
}

// ---- Your existing Blog Post Component ----
export default async function BlogPost({ params }: Props) {
  const { slug } = await params;
  const post = getPost(slug);

  if (!post) {
    notFound();
  }

  // ---- NEW: JSON-LD Structured Data (Schema.org) ----
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: post.title,
    description: post.excerpt || post.description || "",
    image: `/blog/${slug}/opengraph-image.png`,
    datePublished: post.publishedAt,
    dateModified: post.updatedAt || post.publishedAt,
    author: {
      "@type": "Person",
      name: "Tremonte", // Change this to your name
      url: "https://tremonte.info/about", // Optional
    },
    publisher: {
      "@type": "Organization",
      name: "Tremonte.info",
      url: "https://tremonte.info",
    },
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": `https://tremonte.info/blog/${slug}`,
    },
  };

  return (
    <>
      {/* Inject JSON-LD into the head/body */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* Your existing post layout. Keep this exactly as you had it. */}
      <section className="container max-w-3xl py-12">
        <h1 className="font-display text-4xl font-bold tracking-tight">
          {post.title}
        </h1>
        <div className="mt-2 text-sm text-muted-foreground">
          <time dateTime={post.publishedAt}>
            {format(new Date(post.publishedAt), "MMMM d, yyyy")}
          </time>
        </div>
        <article className="prose prose-invert mt-8 max-w-none">
          {post.content}
        </article>
      </section>
    </>
  );
}